---
bibliography: Cap_1.bib
title: "References"
author: "Vanessa Ferreira"
date: "09/06/2019"
fontsize: 12pt
geometry: margin = 1.2in
header-includes:
- \usepackage{placeins}
- \usepackage{fancyhdr}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \onehalfspacing
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage[table]{xcolor}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{placeins}
- \usepackage{tabularx,adjustbox}
- \usepackage[fontsize=12pt]{scrextend}
- \usepackage{dcolumn}
- \usepackage{lmodern}
- \usepackage[T1]{fontenc}
- \usepackage[utf8]{inputenc}
- \usepackage{lastpage}
- \usepackage{indentfirst}
- \usepackage{color}
- \usepackage{graphicx}
- \usepackage{booktabs}
- \usepackage{lscape}
- \usepackage{longtable}
- \usepackage{multirow}
- \usepackage{graphicx}
- \usepackage{microtype}
linestretch: 2
linkcolor: black
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
  word_document: default
urlcolor: black
---

# Documento produzido com Rmarkdown!

## Criando um file .bibtex para integrar Mendeley e Rmarkdown:

- Baixe o Mendeley para Desktop. Entre no site e adicione o login que fizeram hoje em sala. A página Parace como na figura abaixo:



- Depois entre no Mendeley na barra de ferramentas em "Tools" em clique em "Options



- Em "Options" abra a aba "Bibtex"



- Selecione os itens indicados pelas setas nas imagens e escreva na parte em branco o caminho. Esse é o diretório de todas as coisas referentes ao Rmarkdown onde você está trabalhando.


-Pressione o "Sync"



- Confirme se no seu diretório de trabalho encontra arquivos escritos "BibteX Database"


Pronto! Como eu tenho uma pasta para cada referência, tenho várias pastas. Mas você pode ter só uma ou até mesmo salvar somente uma referência! 
Salve em um pendrive ou envie para o seu e-mail para podermos trabalhar com isso em sala de aula. Um exemplo do uso é agora eu citar `[@Benyamini1999]` e aparecer como [@Foundation2018] no texto e nas referências abaixo! mais vbal balb a[@Marchetti1996; @WorldBank2018]. [@Duthe2010; @Foundation2018; @WorldBank2018].
Tentando fazer com que caracteres especiais apareçam: saõ joão demias uai ççççãaãããããããã~fu¨dd

## References


